export const hours = [
  {
    id: 'artDirector',
    name: 'Арт директор',
    bmHours: 22,
    bmModuleHours: 18,
    bmWithoutPromotionHours: 22,
    promotionHours: 4,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'illustratorSenior',
    name: 'Иллюстратор сениор',
    bmHours: 160,
    bmModuleHours: 160,
    bmWithoutPromotionHours: 160,
    promotionHours: 160,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'illustratorRuk',
    name: 'Руководитель иллюстрации',
    bmHours: 30,
    bmModuleHours: 30,
    bmWithoutPromotionHours: 30,
    promotionHours: 0,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'mainDiz',
    name: 'Старший дизайнер',
    bmHours: 60,
    bmModuleHours: 55,
    bmWithoutPromotionHours: 60,
    promotionHours: 20,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'midleDiz',
    name: 'Мидл дизайнер',
    bmHours: 40,
    bmModuleHours: 30,
    bmWithoutPromotionHours: 40,
    promotionHours: 60,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'mainWebDiz',
    name: 'Старший веб дизайнер',
    bmHours: 160,
    bmModuleHours: 50,
    bmWithoutPromotionHours: 160,
    promotionHours: 0,
    separate: true,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'midleWebDiz',
    name: 'Мидл веб дизайнер',
    bmHours: 60,
    bmModuleHours: 0,
    bmWithoutPromotionHours: 80,
    promotionHours: 30,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'leadDev',
    name: 'Лид разработки',
    bmHours: 0,
    bmModuleHours: 0,
    bmWithoutPromotionHours: 0,
    promotionHours: 0,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'frontendDev',
    name: 'Frontend разработчик',
    bmHours: 250,
    bmModuleHours: 160,
    bmWithoutPromotionHours: 100,
    promotionHours: 10,
    separate: true,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'manager',
    name: 'Менеджмент',
    bmHours: 100,
    bmModuleHours: 20,
    bmWithoutPromotionHours: 100,
    promotionHours: 5,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'qa',
    name: 'Тестирование',
    bmHours: 100,
    bmModuleHours: 40,
    bmWithoutPromotionHours: 100,
    promotionHours: 10,
    additionalPercent: 0,
    additionalHours: 0,
  },
  {
    id: 'content',
    name: 'Контент',
    bmHours: 80,
    bmModuleHours: 50,
    bmWithoutPromotionHours: 80,
    promotionHours: 40,
    additionalPercent: 0,
    additionalHours: 0,
  },
]
